version: '3'
services:
  database:
    image: postgres:10.4
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    container_name: database
    hostname: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080
    restart: always
    command: [npm, run, start]
    container_name: frontend
    hostname: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: always
    command: [npm, run, 'start']
    container_name: backend
    hostname: backend

volumes:
  database:
    driver: local
