version: '3'
services:
  database:
    image: postgres:16.2
    networks:
      - database
    ports:
      - '5432:5432'
    env_file:
      - ./Database/.env
    volumes:
      - ./Database/:/docker-entrypoint-initdb.d
    restart: always
    container_name: database
    hostname: database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - Pregonanto
    ports:
      - 8080:8080
    restart: always
    # command: ['./wait-for-it.sh', 'backend:3000', '--', 'nginx', '-g', 'pid /tmp/nginx.pid; daemon off;']
    command: [npm, run, dev]
    container_name: frontend
    hostname: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - Pregonanto
      - database
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: always
    # command: ['./wait-for-it.sh', 'database:5432', '--', 'npm', 'run', 'start:dev']
    command: [npm, run, 'start:dev']
    container_name: backend
    hostname: backend

networks:
  Pregonanto:
    driver: bridge
  database:
    driver: bridge

volumes:
  database:
    driver: local