version: '3.8'

services:
  database:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    container_name: database
    hostname: database
    tty: true
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080
    restart: always
    container_name: frontend
    hostname: frontend
    tty: true
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - database
    restart: always
    container_name: backend
    hostname: backend
    tty: true
    env_file:
      - .env

volumes:
  database:
    driver: local
