import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import PublicContext from "@/contexts/PublicContext";
import Providers from "@/components/Providers";
import SuperImage from "@/components/SuperImage";
import TwoFactorAuthenticationGuard from "@/components/TwoFactorAuthenticationGuard";
import LoginGuard from "@/components/LoginGuard";

const flags = localFont({
	src: "../public/TwemojiCountryFlags.woff2",
	variable: "--flag",
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const cookieStore = cookies();
	const accessToken = cookieStore.get("access_token");

	return (
		<html suppressHydrationWarning lang="en" className="dark">
			<body className={poppins.className + " bg-black " + flags.variable}>
				<Providers accessToken={accessToken}>
					<div className="min-w-screen grid min-h-screen grid-cols-1">
						<div className="fixed inset-0 overflow-hidden bg-gradient-to-t from-background to-accent to-[250%]">
							<SuperImage
								width={1280}
								height={720}
								alt="Background"
								className="z-10 h-full w-full scale-150 object-cover mix-blend-overlay "
								src="/background2.png"
							/>
							<div className="absolute bottom-0 h-full w-full bg-gradient-to-t from-black from-50% to-transparent"></div>
						</div>
						<LoginGuard>
							<Navbar />
							<div className="z-10 flex h-full w-full justify-center pt-28">
								<TwoFactorAuthenticationGuard>
									{children}
								</TwoFactorAuthenticationGuard>
							</div>
						</LoginGuard>
					</div>
					{/* <footer className="relative w-full h-64  bg-card-400 bottom-0
						after:content-[''] after:bg-gradient-to-t after:from-card-400 after:absolute after:-translate-y-full after:to-transparent
					
					">

					</footer> */}
				</Providers>
			</body>
		</html>
	);
}
