interface Bullshit {
	verbs: string[];
	adjectives: string[];
	nouns: string[];
}

export default function generateBullshitExpression(bsType: string): string {
	const pileOfBullshit: Bullshit = populateBullshit(bsType);

	let adjective, verb, noun;

	do {
		verb =
			pileOfBullshit.verbs[
				Math.floor(Math.random() * pileOfBullshit.verbs.length)
			];
		adjective =
			pileOfBullshit.adjectives[
				Math.floor(Math.random() * pileOfBullshit.adjectives.length)
			];
		noun =
			pileOfBullshit.nouns[
				Math.floor(Math.random() * pileOfBullshit.nouns.length)
			];
	} while (
		pileOfBullshit.adjectives.includes(noun) ||
		pileOfBullshit.adjectives.includes(verb) ||
		pileOfBullshit.nouns.includes(adjective) ||
		pileOfBullshit.nouns.includes(verb) ||
		pileOfBullshit.verbs.includes(adjective) ||
		pileOfBullshit.verbs.includes(noun)
	);

	const bullshitExpression = `${verb} ${adjective} ${noun}`;
	return bullshitExpression;
}

function populateBullshit(bsType: string): Bullshit {
	let verbs: string[], adjectives: string[], nouns: string[];
	if (bsType.includes("politicalBS")) {
		// Political
		verbs = ["polled", "voted", "revoked"];
		adjectives = ["highly", "likely"];
		nouns = ["five", "four", "three"];
	} else if (bsType.includes("cryptoBS")) {
		// Crypto
		verbs = [
			"accrue",
			"adapt",
			"adopt",
			"airdrop",
			"algo-trade",
			"allocate",
			"analyze",
			"arbitrage",
			"atomic swap",
			"attack",
			"auction",
			"audit",
			"authenticate",
			"authorize",
			"benchmark",
			"burn",
			"burned",
			"buy",
			"capitalize",
			"capitulate",
			"chain",
			"chain linking",
			"commoditize",
			"compute",
			"confirm",
			"convert",
			"converting",
			"cryptojacking",
			"decentralize",
			"decrypt",
			"decrypting",
			"deflate",
			"dump",
			"encrypt",
			"encrypting",
			"enforce",
			"exchange",
			"fork",
			"front run",
			"halving",
			"hash",
			"hodl",
			"index",
			"initialize",
			"innovate",
			"invest in",
			"limit",
			"mine",
			"mint",
			"network",
			"order",
			"pre-sale",
			"process",
			"proof of",
			"pump",
			"rank",
			"register",
			"regulate",
			"rehypothecate",
			"replicate",
			"revoke",
			"reward",
			"scrape",
			"sell",
			"service",
			"shard",
			"sharding",
			"shill",
			"short",
			"signal",
			"signing",
			"stake",
			"swap",
			"trade",
			"transact",
			"transmit",
		];
		adjectives = [
			"abnormal",
			"absolute",
			"abstract",
			"accredited",
			"active",
			"adaptive",
			"air gapped",
			"algorithmic",
			"alpha",
			"anti-dump",
			"asset-backed",
			"asynchronous",
			"autonomous",
			"bearish",
			"beta",
			"black swan",
			"block",
			"bullish",
			"centralized",
			"cloud",
			"cold storage",
			"collateralized",
			"composable",
			"computed",
			"concentrated",
			"confirmed",
			"confirmed",
			"cross-chain",
			"cryptographic",
			"custodial",
			"cyber",
			"dark web",
			"decentralized",
			"decrypted",
			"defi",
			"deterministic",
			"digital",
			"distributed",
			"encrypted",
			"escrowed",
			"fibonacci",
			"forked",
			"fractional",
			"frictionless",
			"fungible",
			"genesis",
			"governance",
			"hard",
			"hardware",
			"hashed",
			"immutable",
			"initial",
			"integrated",
			"marketed",
			"meta",
			"mineable",
			"multi-signature",
			"multipooled",
			"networked",
			"non-fungible",
			"nonced",
			"off-chain",
			"off-ledger",
			"offline",
			"on-chain",
			"online",
			"open-sourced",
			"p2p",
			"passive",
			"peer to peer",
			"pegged",
			"permissioned",
			"permissionless",
			"perpetual",
			"principled",
			"private",
			"processed",
			"proof of stake",
			"proof of work",
			"public",
			"risk acceptance",
			"securely",
			"segregated",
			"serviced",
			"smart",
			"soft",
			"swap",
			"technical",
			"tokenless",
			"transactional",
			"unconfirmed",
			"unregulated",
			"unspent",
			"volatile",
		];
		nouns = [
			"accounting",
			"accounts",
			"accruals",
			"advantage",
			"AI",
			"algorithms",
			"altcoins",
			"analysis",
			"anonymity",
			"APIs",
			"application",
			"asset",
			"attacks",
			"bag",
			"balance",
			"benchmarks",
			"bitcoin",
			"blockchain",
			"blocks",
			"bots",
			"BTC",
			"cap",
			"capital",
			"chains",
			"ciphers",
			"coin",
			"coins",
			"cold storage",
			"communications",
			"confirmation",
			"consensus",
			"contracts",
			"convergence",
			"costs",
			"crypto",
			"cryptocurrency",
			"cryptography",
			"dapp",
			"darknodes",
			"databases",
			"defi",
			"derivatives",
			"e-signatures",
			"ecosystems",
			"edge nodes",
			"ETH",
			"ether",
			"ethereum",
			"fiat",
			"funds",
			"gains",
			"gas",
			"governance",
			"hash functions",
			"hashes",
			"hashings",
			"ico",
			"indexes",
			"investments",
			"investors",
			"key",
			"ledgers",
			"liquidity",
			"locktimes",
			"margin calls",
			"markets",
			"memecoins",
			"multipools",
			"networks",
			"nodes",
			"output",
			"paper wallets",
			"percentage",
			"percentages",
			"pool",
			"pools",
			"pre-sales",
			"process",
			"programs",
			"proof of stake",
			"proof of work",
			"protocol",
			"protocols",
			"quants",
			"ratios",
			"scamcoins",
			"seeds",
			"services",
			"shit coins",
			"shitcoin",
			"signatures",
			"smart contracts",
			"stablecoin",
			"stablecoins",
			"token",
			"tokens",
			"transactions",
			"volatility",
			"wallet",
			"yield curves",
		];
	} else {
		// Original
		verbs = [
			"aggregate",
			"architect",
			"benchmark",
			"brand",
			"cultivate",
			"deliver",
			"deploy",
			"disintermediate",
			"drive",
			"e-enable",
			"embrace",
			"empower",
			"enable",
			"engage",
			"engineer",
			"enhance",
			"envision",
			"envisioneer",
			"evolve",
			"expedite",
			"exploit",
			"extend",
			"facilitate",
			"generate",
			"grow",
			"harness",
			"implement",
			"incentivize",
			"incubate",
			"innovate",
			"integrate",
			"impact",
			"iterate",
			"leverage",
			"matrix",
			"maximize",
			"mesh",
			"monetize",
			"morph",
			"optimize",
			"orchestrate",
			"productize",
			"recontextualize",
			"redefine",
			"reintermediate",
			"reinvent",
			"repurpose",
			"revolutionize",
			"scale",
			"seize",
			"strategize",
			"streamline",
			"syndicate",
			"synergize",
			"synthesize",
			"target",
			"transform",
			"transition",
			"unleash",
			"utilize",
			"visualize",
			"whiteboard",
		];
		adjectives = [
			"24/365",
			"24/7",
			"B2B",
			"B2C",
			"back-end",
			"best-of-breed",
			"bleeding-edge",
			"blockchain",
			"bricks-and-clicks",
			"clicks-and-mortar",
			"cloud",
			"collaborative",
			"compelling",
			"cross-platform",
			"cross-media",
			"customized",
			"cutting-edge",
			"distributed",
			"dot-com",
			"down stream",
			"dynamic",
			"e-business",
			"efficient",
			"end-to-end",
			"enterprise",
			"extensible",
			"frictionless",
			"front-end",
			"global",
			"granular",
			"holistic",
			"impactful",
			"innovative",
			"integrated",
			"interactive",
			"intuitive",
			"killer",
			"leading-edge",
			"magnetic",
			"mission-critical",
			"next-generation",
			"one-to-one",
			"open-source",
			"out-of-the-box",
			"plug-and-play",
			"proactive",
			"real-time",
			"revolutionary",
			"rich",
			"robust",
			"scalable",
			"seamless",
			"sexy",
			"sticky",
			"strategic",
			"synergistic",
			"transparent",
			"turn-key",
			"ubiquitous",
			"user-centric",
			"upstream",
			"value-added",
			"venture",
			"vertical",
			"viral",
			"virtual",
			"visionary",
			"web-enabled",
			"wireless",
			"world-class",
		];
		nouns = [
			"action-items",
			"ai",
			"applications",
			"architectures",
			"bandwidth",
			"channels",
			"communities",
			"content",
			"convergence",
			"dark web",
			"deliverables",
			"e-business",
			"e-commerce",
			"e-markets",
			"e-services",
			"e-tailers",
			"experiences",
			"eyeballs",
			"functionalities",
			"infomediaries",
			"infrastructures",
			"initiatives",
			"interfaces",
			"machine learning",
			"markets",
			"methodologies",
			"metrics",
			"mindshare",
			"models",
			"networks",
			"niches",
			"paradigms",
			"partnerships",
			"platforms",
			"portals",
			"relationships",
			"ROI",
			"SaaS",
			"start ups",
			"synergies",
			"web-readiness",
			"schemas",
			"solutions",
			"supply-chains",
			"systems",
			"technologies",
			"users",
			"vortals",
			"web services",
		];
	}
	const pileOfBullshit: Bullshit = {
		verbs,
		adjectives,
		nouns,
	};

	return pileOfBullshit;
}
